name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gera o SVG da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: cmarih
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publica no branch `output`
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
